version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install pytest
      - python -m pip install virtualenv
      - virtualenv -p $(which python) ~/efs-utils-virtualenv
      - source ~/efs-utils-virtualenv/bin/activate
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Pre-Build"
      

  build:
    commands:
      - echo "Build phase"
      # Add build-related commands here if needed

  post_build:
    commands:
      - echo "Post-build phase"
      - name: Run all tests
        run: |
          source ~/efs-utils-virtualenv/bin/activate
          make test

artifacts:
  files: 
    - '**/*'  # Include all files in the build artifacts

    
