version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  pre_build:
    commands:
      - echo "Pre-build phase"
      - python -m pip install --upgrade pip
      - python -m pip install virtualenv
      - virtualenv -p $(which python) ~/efs-utils-virtualenv
      - source ~/efs-utils-virtualenv/bin/activate
      - pip install -r requirements.txt
      

  build:
    commands:
      - echo "Build phase"
      - source ~/efs-utils-virtualenv/bin/activate
      - make test

  post_build:
    commands:
      - echo "Post-build phase"
      

artifacts:
  files: 
    - '**/*'  

    
